# Generated by Django 4.1.7 on 2023-03-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_rename_user_recipe_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cover",
            field=models.ImageField(
                default="", null=True, upload_to="recipes/covers/%Y/%m/%d/"
            ),
        ),
    ]
