# Generated by Django 4.1.7 on 2023-03-07 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_recipe_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="recipes.category",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cover",
            field=models.ImageField(
                blank=True, default="", upload_to="recipes/covers/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.CharField(max_length=165),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="preparation_time_unit",
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="serving_unit",
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="title",
            field=models.CharField(max_length=65),
        ),
    ]
