# Generated by Django 4.1.7 on 2023-03-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_alter_recipe_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
