# Generated by Django 4.1.7 on 2023-03-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tag", "0001_initial"),
        ("recipes", "0008_alter_recipe_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(blank=True, default="", to="tag.tag"),
        ),
    ]
