# Generated by Django 4.1.7 on 2023-03-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tag", "0002_remove_tag_content_type_remove_tag_object_id"),
        ("recipes", "0010_alter_recipe_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={},
        ),
        migrations.AlterField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(to="tag.tag"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="title",
            field=models.CharField(max_length=65),
        ),
    ]
